### ISSUE TITLE
mremoteng-portable.exe triggers UAC prompt

### ISSUE THREAD

**Issue by xylltch** [portapps/mremoteng-portable#23]
### Behaviour

UAC prompt triggers when launching the app.

#### Steps to reproduce this issue

1. run mremoteng-portable.exe
2. User Account Control prompt triggers to allow application to execute

#### Expected behaviour

>mRemoteNG launches without UAC prompting to allow execution (mRemoteNG.exe contained in archive [here](https://github.com/mRemoteNG/mRemoteNG/releases/download/v1.76.20/mRemoteNG-Portable-1.76.20.24669.zip) does not trigger UAC when launched).

#### Actual behaviour

> User Account Control prompt triggers to allow application to execute

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 1.76.20-9 win32

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro x64

**Winver screenshot** :

![winver_dUJbN4MS5G](https://user-images.githubusercontent.com/60051187/103602840-a8619c00-4ed2-11eb-8ed5-c98902510d06.png)

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

[mremoteng-portable.log](https://github.com/portapps/mremoteng-portable/files/5767921/mremoteng-portable.log)

**Comment by xylltch** [comment]
I just had a thought, would this be because of the symlinks that are generated in the \app directory? It looks like mremoteng-portable.exe generates those 3 symlinks (for extApps.xml, mRemoteNG.settings, and pnlLayout.xml) each time it is launched, regardless of whether the symlinks already exist. If these are necessary, could it simply check to see if entries already exist for those locations and skip generating new symlinks if they do?

If it's happening for a totally different reason than ignore my suggestion; I'm just making an assumption here.

**Comment by crazy-max** [comment]
Because configuration path cannot be customized, we have to create symlinks and on Windows admin rights are required to create them. You can switch to Tabby if you want: https://portapps.io/app/tabby-portable/
